# Generated by Django 4.2.7 on 2023-11-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='vehichle_id',
            new_name='vehicle_id',
        ),
    ]
