# Generated by Django 4.2.7 on 2023-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_vehichle_id_rental_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
