# Generated by Django 4.2.7 on 2023-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rental_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='location',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('QRIS', 'QRIS'), ('M_BANKING', 'M-Banking')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('PENDING', 'Pending'), ('SUCCESS', 'Success')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
